[postgres]
host = "ep-square-fog-adtjr6b4-pooler.c-2.us-east-1.aws.neon.tech"
port = 5432
user = "neondb_owner"
password = "npg_HbLSwyUTMe24"
database = "neondb"
sslmode = "require"

[security]
admin_password = "VcuDmc2018!"
