[postgres]
DATABASE_URL = "postgresql://neondb_owner:npg_HbLSwyUTMe24@ep-square-fog-adtjr6b4-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
host = "ep-square-fog-adtjr6b4-pooler.c-2.us-east-1.aws.neon.tech"
port = 5432
user = "neondb_owner"
password = "npg_HbLSwyUTMe24"
database = "neondb"
sslmode = "require"

[security]
admin_password = "VcuDmc2018!"

POINTS_BOARD_PASSWORD = "VcuDmc2025!"

