# .streamlit/config.toml

[server]
headless = true  # run without a browser on the host

[browser]
gatherUsageStats = false  # opt out of telemetry

[theme]
base = "light"            # or "dark"
primaryColor = "#2563eb"  # optional brand color
